source 'https://rubygems.org'

gem 'kitchen-ansible'
gem 'kitchen-docker'
gem 'scl'
gem 'kitchen-verifier-serverspec'
gem 'kitchen-vagrant'
gem 'serverspec'
gem 'inspec'
gem 'net-ssh'
gem 'net-scp'
gem 'test-kitchen'
gem 'vault'
